### ISSUE TITLE
Geyser compatibility – bedrock 

### ISSUE THREAD

**Issue by YosephFr** [efeketket/furnicraft#1]
a cordial greeting

I installed the datapack on my server and it is wonderful, I really love it.

I would like to ask you if there is any way to make it compatible with bedrock, I have the geyser plugin installed, when entering from the mobile the textures do not load (only the one on the workbench) and in the console geyser sends some errors like these:

[11:43:18 WARN]: [Geyser-Spigot] Could not find an entity definition with type BLOCK_DISPLAY

Would it be possible at some point to create a resource pack or similar to support this datapack?

**Comment by efeketket** [comment]
Hey, thanks for the feedback! I'm not enough great at texture packing and don't have much time. Since it's an open-source project, feel free to take it on or find someone for the bedrock version. Have a nice day!
