### ISSUE TITLE
Server TPS drops when multiple item stacks are stored in carpenter benches

### ISSUE THREAD

**Issue by gum-star** [efeketket/Furnicraft#11]
The carpenter bench causes server TPS to drop while more than one item stack is being stored inside its chest. On weaker PCs, a severe TPS drop can be produced with just one or two carpenter benches containing items in both ingredient slots.

**Comment by efeketket** [comment]
I do my best to make datapack best optimization. This little things may causes tps drops u right. I tried to solve it with when player is far away from carpenter bench, it drops rest materials placed by player inside to it. Also it's not working when no near player opened it. When opened, it works till this player about 5 block get far away to it.
