### ISSUE TITLE
Mob head

### ISSUE THREAD

**Issue by unimpressedwillow** [efeketket/Furnicraft#12]
The carpenter bench is placed like a mob head for some reason. It places normally in single player, but in my friend's online server, it's just a mob head.
![image](https://github.com/user-attachments/assets/6bef2195-6134-4307-8e6c-d8dac1f7edb5)

**Comment by efeketket** [comment]
When you reloading server, can you see datapack reload message? It may one of your other datapack conflicting with pack.
