### ISSUE TITLE
Can't sit more than once in chairs

### ISSUE THREAD

**Issue by Jotamer** [efeketket/Furnicraft#15]
i can sit only once in a chair, if i want to use it again i have to break it and place it again

https://github.com/user-attachments/assets/1dc68021-8ded-4760-b38a-a7f9e83e5db5

I didn't find a better way to wxplain what happens

**Comment by efeketket** [comment]
Hey! Thanks for the feedback. Shift + Right Click to it. Its minor bug about mob sit mechanic. I'll fix it at next update.
