### ISSUE TITLE
FurniCraft Datapack not working after server restart

### ISSUE THREAD

**Issue by Benny-21** [efeketket/Furnicraft#16]
Hi! In my 1.21 paper server, while the datapacks works amazing, after restarting it I still have my furnitures, but if I try to place a new one I just place instead an head. I can craft etc but not place. Any idea? Thank you!

**Comment by Benny-21** [comment]
Only error about the datapack: [Server thread/WARN]: Not all defined tags for registry ResourceKey[minecraft:root / minecraft:entity_type] are present in data pack: ketket_furnitures:blockcheckers, ketket_furnitures:cantsit

**Comment by efeketket** [comment]
Rarely, furniture cannot be placed. It's about the server tick rate. Break bugged furniture item. Craft a new one and try to place it. 

Second one, It's no big deal. I just added some entites to keep them from sitting on the chair.

**Comment by MagmaBro123** [comment]
> Rarely, furniture cannot be placed. It's about the server tick rate. Break bugged furniture item. Craft a new one and try to place it.
> 
> Second one, It's no big deal. I just added some entites to keep them from sitting on the chair.

Please see my issue.
