### ISSUE TITLE
Interaction in chat when I place furniture

### ISSUE THREAD

**Issue by jennandtonic105** [efeketket/Furnicraft#7]
With some furniture, I get an interaction in chat (it says "hi") when I place it.  Is this a setting I can turn off?

Thank you!

**Comment by efeketket** [comment]
ups, i just forgot to remove it before releasing update. its my test function. i will fix it in next update. its not really important thing. its just saying hi to you.

Thanks for the report!

**Comment by jennandtonic105** [comment]
Not a problem, just wanted to be sure there wasn't a setting I had wrong!
