### ISSUE TITLE
Street Lamp Pole drops chain

### ISSUE THREAD

**Issue by Wanuy** [efeketket/Furnicraft#8]
When breaking the Street Lamp Pole it drops a chain in addition to the pole 'Block'

**Comment by spaceyboii** [comment]
Yes, doesn't even drop the pole block for me. It's still there even after I removed it.

**Comment by efeketket** [comment]
Thanks for the feedback! I'll fix it in the next update. For now, you can remove the remaining pole by using the command /kill @e[tag=poleblock,distance=..1] when you are within 1 block of it.
