### ISSUE TITLE
Issue with the datapack when installing in a server

### ISSUE THREAD

**Issue by GH4r4** [efeketket/Furnicraft#9]
So here is the thing I downloaded the datapack and everything and have the achievement and crafting recipe for the work bench but as soon I place it, it just becomes a head and no working workbench the data packs.

**Comment by GH4r4** [comment]
The furnitures that I have tested to use in the singleplayer mode 1.21 you can only sit on the furnitures just once and when you get off you can sit on there anymore

**Comment by efeketket** [comment]
Fixed at latest update. With Shift+Right click you can make the chair sitable. Thanks for report!
